// Auto-generated by sita (sita/pipeline/design.py). Re-run `sita build`
// to change; hand-edits will be overwritten on the next run.

export type ThemeName = 'slate' | 'paper' | 'bold' | 'niche';

export interface SiteConfig {
  name: string;
  domain: string;
  theme: ThemeName;
  accent: `#${string}`;
  niche: string;
  tagline?: string;
}

export const site: SiteConfig = {
  name: "Pokemon Fire Ash",
  domain: "pokemon-fire-ash.pages.dev",
  theme: "niche",
  accent: "#e63946",
  niche: "pokemon fire ash",
  tagline: "Download and play the fan-made RPG that follows Ash Ketchum's journey through every anime region",
};

/** Full canonical origin, used by astro.config.mjs and BaseLayout. */
export const siteUrl = `https://${site.domain}`;
